apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: metabase
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "metabase"
  MB_DB_PORT: "5432"
  MB_DB_HOST: "postgres-service.postgres.svc.cluster.local"
  JAVA_TIMEZONE: "Asia/Kolkata"
