apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - cert.yaml
  - ingress-route.yaml
