apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-custom-cert
  namespace: monitoring
spec:
  secretName: uptime-kuma-custom-tls
  issuerRef:
    name: spnw-intermediate-ca1-issuer
    kind: ClusterIssuer
  dnsNames:
    - uptime-kuma.home.local
