apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-ingress
  namespace: homarr
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  tls:
    secretName: homarr-custom-tls
  routes:
    - match: Host(`homarr.home.local`)
      kind: Rule
      services:
        - name: homarr
          port: 7575
