apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tinyauth-cert
  namespace: tinyauth
spec:
  secretName: tinyauth-tls
  issuerRef:
    name: spnw-intermediate-ca1-issuer
    kind: ClusterIssuer
  dnsNames:
    - tinyauth.home.local
