apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tinyauth
  namespace: tinyauth
  labels:
    app: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      volumes:
        - name: root-ca
          secret:
            secretName: my-root-ca-secret
      containers:
        - name: tinyauth
          image: ghcr.io/steveiliop56/tinyauth:v3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: root-ca
              mountPath: /etc/ssl/certs/my-root-ca.crt
              subPath: my-root-ca.crt
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: tinyauth-secret
                  key: secretKey
            - name: GENERIC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tinyauth-secret
                  key: clientID
            - name: GENERIC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tinyauth-secret
                  key: clientSecret
            - name: NODE_EXTRA_CA_CERTS
              value: /etc/ssl/certs/my-root-ca.crt
          envFrom:
            - configMapRef:
                name: tinyauth-configmap
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
      # Incase you get DNS resolve issues
      hostAliases:
        - hostnames:
          - zitadel.home.local
          ip: 192.168.0.63
