apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: superset-cert
  namespace: superset
spec:
  secretName: superset-tls
  issuerRef:
    name: spnw-intermediate-ca1-issuer
    kind: ClusterIssuer
  dnsNames:
    - superset.home.local
