apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zitadel-data
  namespace: zitadel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
