apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel-custom-cert
  namespace: zitadel
spec:
  secretName: zitadel-custom-tls
  issuerRef:
    name: spnw-intermediate-ca1-issuer
    kind: ClusterIssuer
  dnsNames:
    - zitadel.home.local
