apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: checkmk-cert
  namespace: checkmk
spec:
  secretName: checkmk-tls
  issuerRef:
    name: spnw-intermediate-ca1-issuer
    kind: ClusterIssuer
  dnsNames:
    - checkmk.home.local
