#cloud-config

# Basic system setup
hostname: HOSTNAME
fqdn: HOSTNAME.example.com

# User setup configuration
users:
  - name: USERNAME
    gecos: K3s User
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    homedir: /home/USERNAME
    shell: /bin/bash
    ssh_authorized_keys:
      - SSH_KEY

# Change passwords for exampleuser using chpasswd
chpasswd:
  expire: false
  users:
  - {name: USERNAME, password: PASSWORD, type: text}

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [ docker ]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - unattended-upgrades

runcmd:
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable docker
  - systemctl start docker

final_message: "The system is finally up, after $UPTIME seconds"
